included:
  - Pokepedia

excluded:
  - ${PWD}/Pods

disabled_rules:
- trailing_whitespace
- function_body_length
- type_body_length
- identifier_name
- line_length
- cyclomatic_complexity
- file_length
- force_try
- force_cast
